{{- if and .Values.ssl.enabled .Values.ssl.mtls }}
{{- if .Values.ssl.mtls.enabled }}
{{- $dot := . }}
{{- range $idx, $caCert := .Values.ssl.mtls.clientCaCerts }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "traefik.fullname" $dot }}-client-ca-certs-{{ $idx }}
  labels:
    app: {{ template "traefik.name" $dot }}
    chart: "{{ $dot.Chart.Name }}-{{ $dot.Chart.Version }}"
    release: {{ $dot.Release.Name | quote }}
    heritage: {{ $dot.Release.Service | quote }}
type: Opaque
data:
  tls.ca: {{ $caCert | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
