{{- if not .Values.ssl.upstream }}
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: {{ template "traefik.fullname" . }}-global
  labels:
    app: {{ template "traefik.name" . }}
    chart: {{ template "traefik.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
{{- if .Values.ssl.tlsMinVersion }}
  minVersion: {{ .Values.ssl.tlsMinVersion | quote }}
{{- end }}
{{- if .Values.ssl.cipherSuites }}
  {{ template "traefik.ssl.cipherSuites" . }}
{{- end }}
{{- if .Values.ssl.mtls }}
{{- if .Values.ssl.mtls.enabled }}
  clientAuth:
    secretNames:
    {{- $fullName := include "traefik.fullname" . -}}
    {{- range $idx, $caCert := .Values.ssl.mtls.clientCaCerts }}
      - {{ $fullName }}-client-ca-certs-{{ $idx }}
    {{- end }}
    clientAuthType: {{ .Values.ssl.mtls.clientAuthType | default "RequireAndVerifyClientCert" | quote }}
{{- end }}
{{- end }}
  {{- if .Values.ssl.sniStrict }}
  sniStrict: true
  {{- end }}
{{- end }}
